# Generated by Django 4.1.2 on 2022-11-16 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the `title` of the content.', max_length=128, verbose_name='title')),
                ('description', models.TextField(help_text='the `description` of the content.', max_length=1000, verbose_name='description')),
                ('numberOfRates', models.PositiveIntegerField(default=0, help_text='the `Number of rates` of the content.', verbose_name='Number of rates ')),
                ('averageRate', models.PositiveIntegerField(default=0, help_text='the `sales number` of the content.', verbose_name='Average rate')),
            ],
        ),
        migrations.CreateModel(
            name='rateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='rate')),
                ('content', models.ForeignKey(help_text='content', on_delete=django.db.models.deletion.CASCADE, to='blog.contentmodel', verbose_name='content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
