# Generated by Django 4.1.2 on 2022-11-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='averageRate',
            field=models.FloatField(default=0, help_text='the `sales number` of the content.', verbose_name='Average rate'),
        ),
    ]
